name: Compile and release

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Set environment variables
        run: echo SCRIPTS_PATH=$(pwd) >> $GITHUB_ENV
      - name: Setup SourcePawn Compiler ${{ matrix.SM_VERSION }}
        id: setup_sp
        uses: rumblefrog/setup-sp@master
        with:
          version: "1.10.x"
          version-file: ./scripting/CR_Weapons.sp

      - name: Compile plugins
        run: |
          mkdir plugins
          cd scripting
          mkdir include
          wget "https://raw.githubusercontent.com/komashchenko/PTaH/master/PTaH.inc" -O include/PTaH.inc
          wget "https://raw.githubusercontent.com/SomethingFromSomewhere/Custom-Rounds/master/scripting/include/custom_rounds.inc" -O include/custom_rounds.inc
          spcomp -E -w234 -O2 -v2 -i"include" -o"../plugins/CR_Weapons.smx" CR_Weapons.sp
          echo "===OUT FILES==="
          cd ../plugins
          ls
          echo "===VERSION==="
          echo ${{ steps.setup_sp.outputs.plugin-version }}
        working-directory: ${{ env.SCRIPTS_PATH }}

      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Zip output
        run: |
          zip -qq -r CR-Weapons-${{ steps.setup_sp.outputs.plugin-version }}.zip plugins
        working-directory: ${{ env.SCRIPTS_PATH }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ steps.setup_sp.outputs.plugin-version }}
          artifacts: "CR-Weapons-${{ steps.setup_sp.outputs.plugin-version }}.zip"
          draft: false
          allowUpdates: true
          prerelease: false
          replacesArtifacts: true
